name: Install goss
description: GitHub Action that installs goss

author: CDQ AG
branding:
  icon: package
  color: green

inputs:
  version:
    description: goss version to install
    default: latest

runs:
  using: composite
  steps:
    - name: Check version
      id: version
      shell: bash
      env:
        TAG: ${{ inputs.version }}
      run: |
        if [ "$TAG" == "latest" ]; then
          TAG=$(curl -s https://api.github.com/repos/goss-org/goss/releases/latest | jq -r '.tag_name')
        fi

        echo "tag=$TAG" >> $GITHUB_OUTPUT

    - name: Prepare environment
      shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}
      run: |
        GOSS_PATH="$ACTION_PATH/.bin"
        echo "GOSS_PATH=$GOSS_PATH" >> $GITHUB_ENV
        mkdir -p "$GOSS_PATH"

        echo "PATH=$GOSS_PATH:$PATH" >> $GITHUB_ENV

    - name: Download goss
      shell: bash
      env:
        TAG: ${{ steps.version.outputs.tag }}
      run: |
        this_os=$(echo "$RUNNER_OS" | tr '[:upper:]' '[:lower:]')
        this_arch=$(echo "$RUNNER_ARCH" | tr '[:upper:]' '[:lower:]')

        if [ "$this_arch" == "x64" ]; then
          this_arch="amd64"
        fi

        if [ "$this_os" == "macos" ]; then
          this_os="darwin"
        fi

        goss_file="goss-${this_os}-${this_arch}"

        function download() {
          local remote_file_name="$1"
          local local_file_name="$2"
          if [[ -z "$local_file_name" ]]; then
            local_file_name="$remote_file_name"
          fi

          echo "Downloading ${remote_file_name}..."
          curl -sL --fail-with-body "https://raw.githubusercontent.com/goss-org/goss/refs/tags/${TAG}/${remote_file_name}" -o "$GOSS_PATH/${local_file_name}"
          echo "OK"

          echo "Making ${local_file_name} executable..."
          chmod +x "$GOSS_PATH/${local_file_name}"
          echo "Done"
        }

        download "$goss_file" "goss"
        download "kgoss"
        download "dgoss"

        echo "Finished"

    - name: Verify installation
      shell: bash
      run: |
        goss --version
