name: action-install-goss
description: GitHub Action that installs goss

author: CDQ AG
branding:
  icon: package
  color: green

inputs:
  version:
    description: goss version to install
    default: latest

runs:
  using: composite
  steps:
    - name: Check version
      id: version
      shell: bash
      env:
        TAG: ${{ inputs.version }}
      run: |
        if [ "$TAG" == "latest" ]; then
          echo "ℹ️ Fetching latest goss version from GitHub API..."
          TAG=$(curl -s https://api.github.com/repos/goss-org/goss/releases/latest | jq -r '.tag_name')
          echo "ℹ️ Latest version is $TAG"
        else
          echo "ℹ️ Using specified version: $TAG"
        fi

        echo "tag=$TAG" >> $GITHUB_OUTPUT

    - name: Prepare environment
      shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}
      run: |
        echo "ℹ️ Preparing GOSS_HOME..."
        GOSS_HOME="$ACTION_PATH/.bin"
        echo "GOSS_HOME=$GOSS_HOME" >> $GITHUB_ENV
        mkdir -p "$GOSS_HOME"
        echo "ℹ️ OK. Created directory $GOSS_HOME"

        echo "ℹ️ Setting up GOSS_PATH..."
        echo "GOSS_PATH=$GOSS_HOME/goss" >> $GITHUB_ENV
        echo "ℹ️ OK"

        echo "ℹ️ Adding GOSS_HOME to PATH..."
        echo "PATH=$GOSS_HOME:$PATH" >> $GITHUB_ENV
        echo "ℹ️ OK"

    - name: Download goss
      shell: bash
      env:
        TAG: ${{ steps.version.outputs.tag }}
      run: |
        echo "ℹ️ Preparing goss file name for OS and architecture..."
        this_os=$(echo "$RUNNER_OS" | tr '[:upper:]' '[:lower:]')
        this_arch=$(echo "$RUNNER_ARCH" | tr '[:upper:]' '[:lower:]')

        if [ "$this_arch" == "x64" ]; then
          this_arch="amd64"
        fi

        if [ "$this_os" == "macos" ]; then
          this_os="darwin"
        fi

        goss_file="goss-${this_os}-${this_arch}"
        echo "ℹ️ OK. GOSS file: $goss_file"

        function download() {
          local remote_file_name="$1"
          local local_file_name="$2"
          if [[ -z "$local_file_name" ]]; then
            local_file_name="$remote_file_name"
          fi

          local download_url="https://github.com/goss-org/goss/releases/download/${TAG}/${remote_file_name}"
          echo "ℹ️ Downloading ${download_url}..."
          curl -sL --fail-with-body "${download_url}" -o "$GOSS_HOME/${local_file_name}"
          echo "ℹ️ OK"

          echo "ℹ️ Making ${local_file_name} executable..."
          chmod +x "$GOSS_HOME/${local_file_name}"
          echo "ℹ️ OK"
        }

        download "$goss_file" "goss"
        download "kgoss"
        download "dgoss"

        echo "ℹ️ Done"

    - name: Verify installation
      shell: bash
      run: |
        echo "ℹ️ Verifying goss installation..."
        goss --version
        echo "ℹ️ OK"
